modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/Lizard-Of-Oz/Inventorio"


[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "LizardOfOz"
description = "${mod_description}"
logoFile = "icon.png"
displayURL="https://github.com/Lizard-Of-Oz/Inventorio"

[[dependencies.inventorio]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventorio]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"